# Something
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: James's Beta Website
email: jamessowa40@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
James's first Website Building attempt
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jamessowa40
github_username:  jamesso40

# Build settings
markdown: kramdown
